version: "3.9"

services:
  csvserver:
    hostname: csvserver
    image: infracloudio/csvserver:latest
    ports:
      - "9393:9300"
    volumes:
      - ./inputFile:/csvserver/inputdata
    environment:
      - CSVSERVER_BORDER=Orange

  prometheus:
    hostname: prometheus
    image: prom/prometheus:v2.22.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
       - '--web.enable-lifecycle'
       - '--config.file=/etc/prometheus/prometheus.yaml'
